### ISSUE TITLE
cmake versus cmake3

### ISSUE THREAD

**Issue by andreasscherbaum** [EnterpriseDB/mongo_fdw#149]
The autogen.sh script expects "cmake3", however it does not detect when "cmake version 3" is installed as "cmake".

This fails #140 and most likely #135.

Which distribution(s) installs "cmake" as "cmake3"? And can "autogen.sh" handle this problem internally?

**Comment by vaibhavdalvi93** [comment]
Thanks @andreasscherbaum for writing to us.

Your expectation is bit unclear to us. I want you to give more insights on this to make it clear.

Our understanding is:

1] If cmake3 is NOT present, then maybe check cmake version, if it is version 3,
 then use that, else error with correct return code or with meaningfull message.

2] This problem should be handled internally by autogen.sh

3]
> This fails #140 and most likely #135.

As per my understanding, the issue #135 doesn't not look relevant example of this cmake vs cmake3 because this is not the part of autogen.sh. This is MAKE we do for mongo_fdw code compilation after successful compilation of driver. Here, error itself is descriptive and able to describe the problem and halts the compilation.

**Comment by andreasscherbaum** [comment]
This came up when I was writing #151, and the Workflow could no find _cmake3_ on the Ubuntu systems which are used for GitHub Actions.
```
root@diamond:/home/ads# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
root@diamond:/home/ads# cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
root@diamond:/home/ads# apt-cache search cmake3
root@diamond:/home/ads# 
root@diamond:/home/ads# which cmake
/usr/bin/cmake
root@diamond:/home/ads# dpkg -S /usr/bin/cmake
cmake: /usr/bin/cmake
```
There is no package _cmake3_, the _cmake_ package provides a _cmake_ binary which is version 3 of _cmake_. That's it.
I don't know where the _cmake3_ originally came from, or if other distributions actually provide a _cmake3_ binary, but that's not the case on Debian/Ubuntu.

**Comment by vaibhavdalvi93** [comment]
@andreasscherbaum Can you please check if this issue is being fixed at your end or not?

It would be good to close this ticket if this is being fixed.

Thanks,
Vaibhav Dalvi

**Comment by andreasscherbaum** [comment]
Not sure that works as intended:

https://github.com/andreasscherbaum/mongo_fdw/runs/2843401419?check_suite_focus=true

In the end autogen.sh still fails with "cmake3 not found".

It could be helpful to use the CI tests proposed [here](https://github.com/EnterpriseDB/mongo_fdw/pull/151).

**Comment by vaibhavdalvi93** [comment]
Through autogen.sh script, initially we check availability of cmake3 in the system, if cmake3 not present then we use cmake. If cmake also missing then system thrown error should be "cmake not found" but this is NOT happening in your case.

To troubleshoot this issue further, it would be good if you share following details:
1. Please make sure you are on latest HEAD (ceb03dc0218594e128f31e6d9395110710ef504b).
2. Please run following commands on system on which you are facing this issue:
     which  cmake
     which  cmake3
3. Please provide version details of available cmake.
3. Please provide value set for environment variable $PATH.

**Comment by andreasscherbaum** [comment]
Actually, scratch my last comment. I did update my test with a fresh copy of autogen.sh, but apparently missed he last changes.
It's working now:
https://github.com/andreasscherbaum/mongo_fdw/runs/2870857446?check_suite_focus=true
